apiVersion: apps/v1
kind: Deployment
metadata:
  name: walmart-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: walmart-app
  template:
    metadata:
      labels:
        app: walmart-app
    spec:
      containers:
        - name: walmart-container
          image: walmart-app:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: walmart-service
spec:
  selector:
    app: walmart-app
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
